### ISSUE TITLE
Some icons in ShadowDOM are flipped from the incorrect origin

### ISSUE THREAD

**Issue by awikkerink** [BrightspaceUI/icons#92]
| Shady | Shadow |
| --- | --- |
| ![localhost-8081-components-d2l-icons-demo--dir rtl dom laptop with hidpi screen](https://cloud.githubusercontent.com/assets/7862298/19117977/ea194c4a-8ae8-11e6-9aab-64790457b9fd.png) | ![localhost-8081-components-d2l-icons-demo--dir rtl dom shadow laptop with hidpi screen](https://cloud.githubusercontent.com/assets/7862298/19117982/ed1991c0-8ae8-11e6-8c3a-b6721285e114.png) |

**Comment by dlockhart** [comment]
I've created [a defect in iron-iconset-svg](https://github.com/PolymerElements/iron-iconset-svg/issues/80) and a [pull request that resolves it](https://github.com/PolymerElements/iron-iconset-svg/pull/81).

If that gets merged in a timely manor, we can just use that. Otherwise we can look into a workaround similar to what we did for the IE focusable issue.

**Comment by omsmith** [comment]
Fixed in iron-iconset-svg#v2.1.1? https://github.com/PolymerElements/iron-iconset-svg/compare/v2.1.0...v2.1.1

**Comment by dlockhart** [comment]
Fixed indeed, with my pull request :)
